
= 我们民族最缺的就是笨人

`本文为在2017年7月1日北大国家发展研究院2017届毕业典礼上，著名作家、北大校友刘震云的嘉宾致辞。`

    感谢各位教授和姚洋院长，让我有机会能够回到母校，回到百年讲堂。我记得我上学的时候它好像是大饭堂，我记得当时每一个北大的同学总会提一个饭袋，饭袋是用羊肚子手巾缝成的。我记得我提了四年饭袋，但是我不记得我洗过那个饭袋。当时大食堂的菜有四个阶级，一个阶级是炒土豆丝、炒洋白菜、炒萝卜丝，这是五分钱的。第二阶级是鸡蛋西红柿、锅塌豆腐，这是一毛钱的。一毛五的才是有肉的，鱼香肉丝、宫煲鸡丁；两毛钱的有回锅肉、红烧肉，还有四喜丸子。我是一个农村孩子，一毛五以上的菜，我在北大四年从来没有接触过，跟它们不熟。我最爱吃的菜是锅塌豆腐，不是肉菜，但是豆腐被炸过，油水比较大，拌米饭！人生不过如此，夫复何求！

　　在大食堂最大的惊喜不是你排队买到了锅塌豆腐，而是当你排到的时候你是最后一个买锅塌豆腐的。因为到最后了，盆里边汤汤水水，大厨一下子都倒入我的盘子里。最悲催的是你前一个同学有锅塌豆腐，到你没有了。他买到锅塌豆腐之后就会看你一眼，这已经到了社会学和心理学的角度，（他）庆幸之余有些幸灾乐祸。

　　最大的奇迹在我身上发生过。等排到我的时候，前面的同学就剩了一份，但这个同学思索了一下，“就剩了最后一份的锅塌豆腐，它一定特别的凉，我改主意了，我想吃鱼香肉丝”，这个锅塌豆腐又到了我的饭盆里。当我吃到锅塌豆腐的时候，我问了一下改吃鱼香肉丝的同学，我说你是哪个系的师兄？他说他是经济系。经济系不就是我们国发院的前身吗？滴水知恩，当涌泉相报！

    我的意思是你跟母校的关系不是你在母校的时候，而是你离开母校的时候，再想起锅塌豆腐的时候，当你十年之后再路过我们北大的时候，再来到百年讲堂的时候。在母校参加这种场合我有过三次，这是第三次。第一次是2013年新生入学的时候，在未名湖旁边的大操场，有一万多名新生，还有中文系百年校庆的时候，还有就是今天——我们国发院有983名同学毕业的时候。入学和毕业还是不一样的，因为入学是相聚，毕业是分别。自古人生伤离别，但是我还是祝贺983名同学毕业，它使我从今天开始在世界的各个角落又多了983名我的同学。

　　我这几年最深的体会，同学是通往世界的一张特别有效的通行证，不管到哪一个国家，不管到世界的哪一个角落，上来他告诉我：师兄，我也是北大的。同学能够把从陌生到熟悉的时间极大的缩短，因为你马上可以谈论一下北大相同的老师，和北大的锅塌豆腐。

　　2015年，法国在里昂有个作家的圆桌会议，我参加。在那里，我又碰到一位同学。大家都知道有一个喷泉特别的出名，就是雕刻自由女神的法国雕塑家做的，这个喷泉只有几匹马，往不同的方向拉，我看到这个雕塑喷水的时候想起了商鞅。

　　我的同学对我说，师兄你在生活中不能上当，我说不能上什么当？他说如果有人请你到外面吃饭，一定不是你的同学。我说，应该到哪里吃饭呢？他说到家里。他说，如果到家里他请你吃牛排也一定是不是你的同学。我说，应该吃什么？他说包饺子。接着我就到这个同学家里包饺子。

    为什么说这个同学呢？因为他是我们国发院MBA毕业的，目前在里昂当教授。这个同学他的家在里昂的郊区，就在河的旁边，我去他家吃饺子，他首先带我到地上看看，说你看我这个小别墅，你看我的车子，你看我的法国女朋友。接着他又带我到他们家地下看看，有一个酒窖，镇窖之宝是1985年的三瓶拉菲红酒，他说：师兄，1985年到2015年是30年，人生有几个30年？今天我们把三瓶拉菲喝了！我说，且慢！我说今天如果喝了，你明天后悔怎么办？他说，有好酒不让同学喝，让谁喝呢？如果不让同学喝，要好酒有什么用呢？他上升到了哲学层次。

　　我也热血沸腾了，说：喝！就着饺子！我还没怎么样，他喝多了。喝多了之后就开始给我讲现代金融学理论，讲外汇市场，讲股票市场，讲现代金融学理论在企业的运用，我一句没听懂，但是拉菲真不错！我的意思是——同学，当你在学校是同学的时候，你并不知道什么是同学，一离开学校再重逢的时候，你才知道什么叫同学。什么叫同学？当他说一晚上话，你一句都听不懂的时候，你还跟他聊一晚上，（这叫同学！）

　　刚才姚洋院长和张维迎教授做了一个特别好的发言，因为他谈到了你们的母校，我的母校——北大是谁，北大是什么人。一代一代的北大人认同，这是新文化运动的中心，是五四运动的策源地，德先生和赛先生的开创地。这里产生了严复、蔡元培、李大钊、陈独秀、胡适等人，蔡先生提出的办学方针是思想自由、兼容并包。这些人虽然所处的时代不同，高矮胖瘦不同，但是有一点是相同的，他们是民族的先驱者。

    什么叫先驱者呢？当几万万同胞还生活在当下的时候，他们在思考这个民族的未来，为了自己的理想，不切实际的理想，甚至他们贡献了自己宝贵的生命。黑暗中没有火炬，我只有燃烧自己，我以我血荐轩辕，哪怕他知道几万万同胞会蘸着他的血来吃馒头，这是我们北大的慈悲。

　　这就牵扯到知识分子存在的必要性。为什么人类需要知识分子？刚才张维迎教授做了一个特别好的阐述。一个民族的知识分子除了要考虑这个民族的过去、当下，最重要的是考虑未来。每一个知识分子的眼睛也像探照灯一样，更多的知识分子像更多的探照灯一样，要照亮这个民族的未来。如果这些探照灯全部都熄灭了，这个民族的前方是黑暗的，用孙中山先生的话，“这个民族会跌入万劫不复的深渊”。

　　我们的校徽是鲁迅先生设计的，鲁迅先生在北大讲过话。读鲁迅先生的作品读来读去，我读出了三个人。一个是我们的父亲阿Q。阿Q最大的特点是什么？最大的特点就是没老婆，出门就挨打。出门挨打不叫受欺负，但是你的智商被欺负了而不自知，你又是我们的父亲，我们就跟着这个父亲受欺负。

　　他还塑造了一个特别好的母亲的形象，就是祥林嫂。祥林嫂最大的特点是什么？没丈夫。一个孩子还被老虎吃了，她一辈子的工作要把她的悲剧讲成喜剧。

　　另外鲁迅先生还塑造了一个知识分子的形象就是孔乙己，孔乙己最大的特点是什么？是腿被打断了。如果知识分子的腿被打断了，他看到的远处，比平常人还要近。那我知道这个民族的知识分子出现像姚洋院长讲的这个民族的现状，一点都不奇怪。兼容并包，思想自由，应该是我们北大人捍卫这个民族的生命。所以大家应该知道，我们的母校是谁，我们的老师是谁。我参加过一次毕业典礼，我觉得今天我听到的姚院长和张教授的发言，是最有质量的临别嘱托。

    另外大家毕业以后是从一所大学到另外一所大学，从一本书到另外一本书，我觉得大家最需要知道的就是这个民族最缺什么。这个民族不缺人，不缺钱，全世界都知道中国人最有钱，我觉得这个说法是最欺负人的。如果14个人有10块钱，另外两个人有9块钱，以我们国发院现代经济学的理论去衡量，到底谁有钱？我们的马路头一年修，第二年就挖开看一看；我们的大桥，很多寿命不会超过30年。一下雨，我们的城市就淹了。缺什么？我们这个民族特别缺远见，远见对我们这个民族如大旱之望云霓，如雾霾之望大风。

　　大家开始在另外一个大学起步的时候，有两句话你千万不要相信。一个是“世界上是不可以投机的”，千万别信，世界是可以投机的；另外一句话，“世界上是没有近路可走的”，这句话不成立，世界上是有近路可走的。投机分子走近路，因此成功的人起码占80%，但主要的区别是：他们得到的利益只是对于他们自己，是你做这些事情，只对你自己好。刚才张维迎教授列举了好多的数字，民族之间的对比，他讲的话希望你们牢记：要做笨人。这个民族最不缺的就是聪明人，最缺的就是笨人。

　　我在北大有很多特别好的导师，我在另外一个学校也有两个特别好的导师。

　　一个是我的外祖母，我外祖母是一个普通的中国农村妇女，她不识字，她1900年出生，1995年去世，活了95年。她在方圆几十里都是个明星，如果她要演电影就是安吉丽娜·朱莉，如果踢足球就是梅西，如果打篮球就是杜兰特，如果跑百米就是博尔特。但是她一辈子都在这里。她的个子只有一米五六。我们黄河边三里路长的麦趟子，她割麦子是速度最快的，当她把麦子从这头割到那头的时候，一米七八的大汉也只割到一半。


    当她晚年的时候，我跟她有一次炉边谈话。我说你为什么割的比别人快？她说我割的不比任何人快，只是三里路长的麦堂子，我只要扎下腰，我从来不直腰，因为你想直1次腰的时候，你就会想直第10次、第200次，我无非是在别人直腰的时候割的比别人更快一点。

　　我有个舅舅，是一个木匠，他小时候种过天花，脸上有一些麻子，所以大家都叫他刘麻子。刘麻子做的箱子在周围40里卖得最好，所以渐渐我们周边就没有木匠了，就剩刘麻子一个人了。所有的木匠说刘麻子这个人毒，所有的顾客都说他做的箱子柜子特别好。

　　他晚年的时候我跟他有一个炉边谈话。我说：你的同行说你毒，你的顾客说你好，你到底是什么人？他说别人说你毒、说你好，并不能使你成为一个好木匠，唯一使我能成为好木匠的是：别人打一个箱子花三天时间，我花六天时间，我比他做得更好；接着他又说，你只花六天时间还不是一个好的木匠，他说我是打心眼里喜欢做木匠，我特别喜欢闻做木匠活刨出来的刨子花的味道；他又说只是喜欢做木匠活，也当不好木匠，有时候我当木匠的时候会有恍惚的时候，就是当我看到一棵树，我看到如果它是一个松木，是一个柏木，是楠木，这要是给哪家姑娘出嫁的手打个箱子该多好；如果它是一棵杨树，杨树是最不成材的，只能打个小板凳。我觉得他已经到达了“空即是色，色即是空”的境界，他虽然不是北大哲学系的，但是他到达了哲学系毕业的水平。

　　我开车路过我们民族的马路，我们民族的马路两边基本上大家会看到都是杨树。为什么？因为杨树长得快。但是你要到其他的国家，像欧洲、北美其他的发达国家，路两旁全是松树、椴树、楠树、橡树、白蜡，树的质量的对比能够代表一个民族的心态。

    所以最后我送在座的师妹和师弟两句话。一句是种树要种松树，做人要做刘麻子；（另一句是）举起你们手里的探照灯，照亮我外祖母没功夫直腰的麦田。最重要的事忘了，记得下次见面的时候请我吃饺子，谢谢。
